# Generated by Django 5.0.6 on 2024-07-04 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookmarkChat',
            fields=[
                ('bookmark_id', models.AutoField(db_column='Bookmark_ID', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='Timestamp')),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'bookmark_chat',
                'db_table_comment': 'This Table Is Used To Store The Bookmarked Chats On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(db_column='Chat_ID', primary_key=True, serialize=False)),
                ('message', models.TextField(db_column='Message')),
                ('timestamp', models.DateTimeField(db_column='Timestamp')),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'chat',
                'db_table_comment': 'This Table Is Used To Store The Chat Details On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatLoginDetails',
            fields=[
                ('login_id', models.AutoField(db_column='Login_ID', primary_key=True, serialize=False)),
                ('last_activity', models.DateTimeField(db_column='Last_Activity')),
                ('is_typing', models.CharField(db_column='Is_Typing', max_length=3)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'chat_login_details',
                'db_table_comment': 'This Table Is Used To Store Login Details of Users Of The Chat On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatStatus',
            fields=[
                ('status_id', models.AutoField(db_column='Status_ID', primary_key=True, serialize=False)),
                ('status', models.IntegerField(db_column='Status')),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'chat_status',
                'db_table_comment': 'This Table Is Used To Store The Chat Status Details On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='Username', max_length=75)),
                ('email_address', models.CharField(db_column='Email_Address', max_length=75, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=75)),
                ('profile_picture', models.CharField(db_column='Profile_Picture', max_length=80)),
                ('current_session', models.IntegerField(db_column='Current_Session')),
                ('online', models.IntegerField(db_column='Online')),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'chat_users',
                'db_table_comment': 'This Table Is Used To Store Users Of The Chat On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('group_id', models.AutoField(db_column='Group_ID', primary_key=True, serialize=False)),
                ('leader_id', models.IntegerField(db_column='Leader_ID')),
                ('group_name', models.CharField(db_column='Group_Name', max_length=75)),
                ('group_image', models.CharField(blank=True, db_column='Group_Image', max_length=75, null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'group_chat',
                'db_table_comment': 'This Table Is Used To Store Groups for the Chat On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('member_id', models.AutoField(db_column='Member_ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_Name', max_length=75)),
                ('created_at', models.DateTimeField(db_column='Created_At')),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'project_members',
                'db_table_comment': 'This Table Is Used To Store Project Member Details On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(db_column='Project_ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_column='Project_Name', max_length=75)),
                ('project_details', models.CharField(db_column='Project_Details', max_length=255)),
                ('project_image', models.CharField(db_column='Project_Image', max_length=75)),
                ('created_at', models.DateTimeField(db_column='Created_At')),
                ('updated_at', models.DateTimeField(blank=True, db_column='Updated_At', null=True)),
                ('start_date', models.DateField(db_column='Start_Date')),
                ('end_date', models.DateField(db_column='End_Date')),
                ('total_days', models.IntegerField(db_column='Total_Days')),
                ('estimated_budget', models.FloatField(db_column='Estimated_Budget')),
                ('actual_expenditure', models.FloatField(db_column='Actual_Expenditure')),
                ('balance', models.FloatField(db_column='Balance')),
                ('project_status', models.CharField(db_column='Project_Status', max_length=9)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'projects',
                'db_table_comment': 'This Table Is Used To Store Project Details For the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resource_id', models.AutoField(db_column='Resource_ID', primary_key=True, serialize=False)),
                ('resource_name', models.CharField(db_column='Resource_Name', max_length=75)),
                ('resource_details', models.CharField(db_column='Resource_Details', max_length=80)),
                ('resource_directory', models.CharField(db_column='Resource_Directory', max_length=75)),
                ('created_at', models.DateTimeField(db_column='Created_At')),
                ('updated_at', models.DateTimeField(blank=True, db_column='Updated_At', null=True)),
                ('resource_status', models.CharField(db_column='Resource_Status', max_length=10)),
                ('resource_type', models.CharField(db_column='Resource_Type', max_length=8)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'resources',
                'db_table_comment': 'This Table Is Used To Store Resource Details On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(db_column='Task_ID', primary_key=True, serialize=False)),
                ('dependant_task_id', models.IntegerField(blank=True, db_column='Dependant_Task_ID', null=True)),
                ('task_name', models.CharField(db_column='Task_Name', max_length=75)),
                ('task_details', models.CharField(db_column='Task_Details', max_length=80)),
                ('task_given_date', models.DateField(db_column='Task_Given_Date')),
                ('task_due_date', models.DateField(db_column='Task_Due_Date')),
                ('task_completed_date', models.DateField(blank=True, db_column='Task_Completed_Date', null=True)),
                ('task_days_left', models.IntegerField(db_column='Task_Days_Left')),
                ('task_days_overdue', models.IntegerField(db_column='Task_Days_Overdue')),
                ('task_percentage_complete', models.FloatField(db_column='Task_Percentage_Complete')),
                ('task_status', models.CharField(db_column='Task_Status', max_length=15)),
                ('created_at', models.DateTimeField(db_column='Created_At')),
                ('updated_at', models.DateTimeField(blank=True, db_column='Updated_At', null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'tasks',
                'db_table_comment': 'This Table Is Used To Store Task Details On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(db_column='Transaction_ID', primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(db_column='Transaction_Name', max_length=75)),
                ('transaction_details', models.CharField(db_column='Transaction_Details', max_length=80)),
                ('transaction_price', models.FloatField(db_column='Transaction_Price')),
                ('transaction_quantity', models.IntegerField(db_column='Transaction_Quantity')),
                ('total_transaction_price', models.FloatField(db_column='Total_Transaction_Price')),
                ('created_at', models.DateTimeField(db_column='Created_At')),
                ('updated_at', models.DateTimeField(blank=True, db_column='Updated_At', null=True)),
                ('transaction_status', models.CharField(db_column='Transaction_Status', max_length=9)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'transactions',
                'db_table_comment': 'This Table Is Used To Store Transaction Details On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='Fullname', max_length=75)),
                ('gender', models.CharField(db_column='Gender', max_length=6)),
                ('phone_number', models.JSONField(db_column='Phone_Number')),
                ('email_address', models.CharField(db_column='Email_Address', max_length=75, unique=True)),
                ('profile_picture', models.CharField(db_column='Profile_Picture', max_length=75)),
                ('user_type', models.CharField(db_column='User_Type', max_length=13)),
                ('created_at', models.DateTimeField(db_column='Created_At')),
                ('updated_at', models.DateTimeField(blank=True, db_column='Updated_At', null=True)),
                ('password', models.CharField(db_column='Password', max_length=80)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': 'This Table Is Used To Store User Details For the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesyncApp.users')),
            ],
        ),
    ]
