# Generated by Django 5.0.6 on 2024-09-01 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0003_alter_chat_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('item_type', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 9, 1, 7, 27, 41, 246991, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'bookmark_chat',
                'db_table_comment': 'This Table Is Used To Store The Bookmarked Items On the System',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='pinnedchat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='pinnedchat',
            name='group',
        ),
        migrations.RemoveField(
            model_name='pinnedchat',
            name='user',
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 7, 27, 41, 246991, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_deleted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_size',
            field=models.CharField(max_length=100),
        ),
    ]
