# Generated by Django 5.0.6 on 2024-07-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0003_remove_otp_is_used_alter_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
