# Generated by Django 5.0.6 on 2024-07-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0004_otp_used_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('contractor', 'Contractor'), ('admin', 'Administrator')], max_length=50),
        ),
    ]
