# Generated by Django 5.0.6 on 2024-09-01 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0006_remove_chat_is_bookmarked_alter_bookmarks_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='bookmarks',
            table_comment='This Table Is Used To Store The Bookmarked Items On the System',
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 10, 42, 0, 439568)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 10, 42, 0, 439568)),
        ),
    ]
