# Generated by Django 5.0.6 on 2024-07-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatLoginDetails',
        ),
        migrations.DeleteModel(
            name='ChatUsers',
        ),
    ]
