# Generated by Django 5.0.6 on 2024-07-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
