# Generated by Django 5.0.6 on 2024-09-03 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0012_remove_bookmarkchat_chat_remove_bookmarkchat_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 14, 28, 9, 458324)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 14, 28, 9, 458324)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
