# Generated by Django 5.0.6 on 2024-09-04 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0014_remove_bookmarkchat_chat_remove_bookmarkchat_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_votes_against',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_votes_for',
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_category',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_type',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 20, 6, 54, 658908)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 20, 6, 54, 658908)),
        ),
    ]
