# Generated by Django 5.0.6 on 2024-07-10 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0015_bookmarkchat_chat_chatstatus_groupchat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(db_column='Event_ID', primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_column='Event_Name', max_length=75)),
                ('event_details', models.CharField(db_column='Event_Details', max_length=80)),
                ('event_date', models.DateField(db_column='Event_Date')),
                ('event_start_time', models.TimeField(db_column='Event_Start_Time')),
                ('event_end_time', models.TimeField(db_column='Event_End_Time')),
                ('event_location', models.CharField(blank=True, db_column='Event_Location', max_length=75, null=True)),
                ('event_link', models.CharField(blank=True, db_column='Event_Link', max_length=80, null=True)),
                ('event_status', models.CharField(db_column='Event_Status', max_length=9)),
                ('created_at', models.DateTimeField(db_column='Created_At')),
                ('updated_at', models.DateTimeField(blank=True, db_column='Updated_At', null=True)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'events',
                'db_table_comment': 'This Table Is Used To Store Event Details On the System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesyncApp.transactions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'transaction')},
            },
        ),
    ]
