# Generated by Django 5.0.6 on 2024-07-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0016_events_transactionvote'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='bookmarkchat',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='chat',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='chatstatus',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='events',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='groupchat',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='projectmembers',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='projects',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='resources',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='tasks',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='transactions',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='users',
            table_comment=None,
        ),
    ]
