# Generated by Django 5.0.6 on 2024-09-06 21:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0017_remove_bookmarkchat_chat_remove_bookmarkchat_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 23, 6, 342557)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 23, 6, 342557)),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='member',
        ),
        migrations.AddField(
            model_name='tasks',
            name='member',
            field=models.ManyToManyField(related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
