# Generated by Django 5.0.6 on 2024-07-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0017_alter_bookmarkchat_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='bookmarkchat',
            table_comment='This Table Is Used To Store The Bookmarked Chats On the System',
        ),
        migrations.AlterModelTableComment(
            name='chat',
            table_comment='This Table Is Used To Store The Chat Details On the System',
        ),
        migrations.AlterModelTableComment(
            name='chatstatus',
            table_comment='This Table Is Used To Store The Chat Status Details On the System',
        ),
        migrations.AlterModelTableComment(
            name='events',
            table_comment='This Table Is Used To Store Event Details On the System',
        ),
        migrations.AlterModelTableComment(
            name='groupchat',
            table_comment='This Table Is Used To Store Groups for the Chat On the System',
        ),
        migrations.AlterModelTableComment(
            name='projectmembers',
            table_comment='This Table Is Used To Store Project Member Details On the System',
        ),
        migrations.AlterModelTableComment(
            name='projects',
            table_comment='This Table Is Used To Store Project Details For the System',
        ),
        migrations.AlterModelTableComment(
            name='resources',
            table_comment='This Table Is Used To Store Resource Details On the System',
        ),
        migrations.AlterModelTableComment(
            name='tasks',
            table_comment='This Table Is Used To Store Task Details On the System',
        ),
        migrations.AlterModelTableComment(
            name='transactions',
            table_comment='This Table Is Used To Store Transaction Details On the System',
        ),
        migrations.AlterModelTableComment(
            name='users',
            table_comment='This Table Is Used To Store User Details For the System',
        ),
    ]
