# Generated by Django 5.0.6 on 2024-09-06 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0018_remove_bookmarkchat_chat_remove_bookmarkchat_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 52, 43, 879007)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 0, 52, 43, 879007)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
