# Generated by Django 5.0.6 on 2024-07-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0018_alter_bookmarkchat_table_comment_and_more'),
    ]

    operations = [
    ]
