# Generated by Django 5.0.6 on 2024-09-06 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0019_remove_bookmarkchat_chat_remove_bookmarkchat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dependant_tasks',
            field=models.ManyToManyField(blank=True, related_name='task_dependencies', to='sitesyncApp.tasks'),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 1, 9, 50, 964387)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 1, 9, 50, 964387)),
        ),
    ]
