# Generated by Django 5.0.6 on 2024-07-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0020_alter_otp_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otp',
            table='otp',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
