# Generated by Django 5.0.6 on 2024-07-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0021_alter_otp_table_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
