# Generated by Django 5.0.6 on 2024-07-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0022_alter_otp_options_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otp',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
