# Generated by Django 5.0.6 on 2024-09-30 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0022_remove_bookmarkchat_chat_remove_bookmarkchat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_transaction_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 9, 8, 29, 293966)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 9, 8, 29, 299025)),
        ),
    ]
