# Generated by Django 5.0.6 on 2024-08-25 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesyncApp', '0023_alter_otp_table_alter_profile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedChat',
            fields=[
                ('pinned_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'pinned_chat',
                'db_table_comment': 'This Table Is Used To Store The Pinned Chats On the System',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('contractor', 'Contractor'), ('quantity surveyor', 'Quantity Surveyor'), ('project manager', 'Project Manager'), ('architect', 'Architect'), ('engineer', 'Engineer'), ('admin', 'Administrator')], max_length=50),
        ),
    ]
